### ISSUE TITLE
[Feat/Plugin] 插件二期

### ISSUE THREAD

**Issue by arvinxx** [lobehub/lobe-chat#97]
在 [一期](https://github.com/lobehub/lobe-chat/issues/73) 的基础框架搭好的情况下，二期重点解决：

- [x] 插件的安全性
   - [x] 需要实现沙盒隔离，以解决读 localStorage 敏感信息窃取的问题 https://github.com/lobehub/lobe-chat/pull/141

- [x] 开发者友好 https://github.com/lobehub/chat-plugin-sdk/issues/2
  - [x] #122
  - [x] #135
  - [x] #150
  - [x] SDK 开发文档  https://github.com/lobehub/chat-plugin-sdk/issues/10
  - [x] https://github.com/lobehub/chat-plugin-sdk/issues/11
  - [x] 开发模板 https://github.com/lobehub/chat-plugin-template
  - [x] 开发案例：[天气插件](https://github.com/lobehub/chat-plugin-realtime-weather)、[搜索引擎](https://github.com/lobehub/chat-plugin-search-engine)
  - [x] 自定义配置插件（最简单的配置） https://github.com/lobehub/chat-plugin-search-engine/issues/2
  - [x] https://github.com/lobehub/chat-plugin-template/issues/1
  - [x] 支持所有模块的独立部署
      - [x] Chat Plugins Gateway https://github.com/lobehub/chat-plugins-gateway#-self-hosting
      - [x] Lobe Chat Plugins  https://github.com/lobehub/lobe-chat-plugins#-self-hosting

- [x] 插件架构的可维护性
   - [x] lobehub/chat-plugins-gateway#4
   - [x] https://github.com/lobehub/lobe-chat/issues/155
- [x] 插件的可扩展性
   - [x] 单一插件支持多 API https://github.com/lobehub/chat-plugin-sdk/issues/5
   - [x] #106
   - [x] lobehub/lobe-chat-plugins#5
   - [x] 提供插件的配置能力 https://github.com/lobehub/chat-plugin-sdk/issues/3

- [x] 插件使用的稳定性，更加精准地呈现异常状态（插件 api 请求状态、meta、manifest 的报错处理）；
  - [x] lobehub/lobe-chat#98
  - [x] #108
  - [x] lobehub/lobe-chat#105

**Comment by canisminor1990** [comment]
https://github.com/lobehub/lobe-chat/issues/149
